Paginate = 4
baseURL = "https://swiftfitevents.com"
description = "Swift Fit Events"
enableGitInfo = true
googleAnalytics = "UA-116675438-1"
languageCode = "en-us"
theme = "kube"
title = "Swift Fit Events"
[[menu.main]]
name = "Activities"
url = "/activities/"
weight = 1
[[menu.main]]
  name = "Virtual Classes"
  url = "/virtual-classes/"
  weight = 2
[[menu.main]]
  name = "Events"
  url = "/events/"
  weight = 2
[[menu.main]]
  name = "On Demand"
  url = "/ondemand/"
  weight = 3
[[menu.main]]
  name = "Shop"
  url = "/shop/"
  weight = 4
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 5
[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 6
[params]
author = "Swift Fit Events"
email = "lee@swiftfitevents.com"
facebook = "swiftfitevents"
github = ""
instagram = "swiftfitevents"
noindex_kinds = ["taxonomy", "taxonomyTerm"]
rsslink = "/index.xml"
[params.seo.webmaster_verifications]
bing = "05C96F6712DC73C89BC6A6D19C3F2FCA"
google = "tjb3E73TVHBZgW8-vjDur6ROKwgG40qhybyWdl9zqYk"
yandex = "7de1aa3ba6cd6d12"
