Paginate = 4
baseURL = "/"
description = "Ranger Running"
languageCode = "en-us"
theme = "kube"
title = "Ranger Running"
googleAnalytics = "UA-116675438-1"
canonifyURLs = true
[[menu.main]]
  name = "Services"
  url = "/services/"
  weight = 1
[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3
[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 4
[params]
  author = "Ranger Running"
  email = "howdy@rangerrunning.com"
  github = ""
  rsslink = "/index.xml"
  instagram = "rangerrunning"
  facebook = "rangerrunning"
[params.seo.webmaster_verifications]
  google = "tjb3E73TVHBZgW8-vjDur6ROKwgG40qhybyWdl9zqYk" # Optional, Google verification code
  bing = "05C96F6712DC73C89BC6A6D19C3F2FCA" # Optional, Bing verification code
  yandex = "7de1aa3ba6cd6d12"
