Paginate = 4
baseURL = "/"
description = "Ranger Running"
languageCode = "en-us"
theme = "kube"
title = "Ranger Running"
[[menu.main]]
  name = "Services"
  url = "/services/"
  weight = 1
[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3
[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 4
[params]
author = "Ranger Running"
email = "myemail@myaddress.xxx"
github = ""
rsslink = "/index.xml"
instagram = "rangerrunning"
facebook = "rangerrunning"
