[context.production.environment]
  HUGO_VERSION = "0.37.1"

[[headers]]
  for = "/*.ttf"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-ttf"

[[headers]]
  for = "/*.otf"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-otf"
