[context.production.environment]
  HUGO_VERSION = "0.36"

[[headers]]
  for = "/font/*.ttf"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-ttf"

[[headers]]
  for = "/font/*.otf"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-otf"
